include Makefile.inc

.PHONY: docker-all docker-base docker-android docker-darwin docker-darwin-sdk-extractor docker-freebsd docker-linux docker-web

# RUNNER is the CLI used to interact with docker or podman
RUNNER := $(shell 2>/dev/null 1>&2 docker version && echo "docker" || echo "podman")

docker-base: .docker-base
.docker-base: base/Dockerfile
	@docker buildx build --platform linux/amd64,linux/arm64 -f ${CURDIR}/base/Dockerfile -t ${REPOSITORY}:${PREFIX}-${VERSION}-base -t ${REPOSITORY}:${PREFIX}-${VERSION}-windows -t ${REPOSITORY}:${PREFIX}-windows -t ${REPOSITORY}:${PREFIX}-${VERSION}-web -t ${REPOSITORY}:${PREFIX}-web --push .
	@touch .docker-base

docker-darwin: .docker-darwin
.docker-darwin: docker-base darwin/Dockerfile
	@docker buildx build --platform linux/amd64,linux/arm64 --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base -f ${CURDIR}/darwin/Dockerfile -t ${REPOSITORY}:${PREFIX}-${VERSION}-darwin -t ${REPOSITORY}:${PREFIX}-darwin --push .
	@touch .docker-darwin

docker-darwin-sdk-extractor: .docker-darwin-sdk-extractor
.docker-darwin-sdk-extractor: docker-base darwin-sdk-extractor/Dockerfile
	@docker buildx build --platform linux/amd64,linux/arm64 --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base -f ${CURDIR}/darwin-sdk-extractor/Dockerfile -t ${REPOSITORY}:${PREFIX}-${VERSION}-darwin-sdk-extractor -t ${REPOSITORY}:${PREFIX}-darwin-sdk-extractor --push .
	@touch .docker-darwin-sdk-extractor

docker-freebsd-base: .docker-freebsd-base
.docker-freebsd-base: docker-base freebsd/base/Dockerfile
	@docker buildx build --platform linux/amd64,linux/arm64 --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base -f ${CURDIR}/freebsd/base/Dockerfile -t ${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-base -t ${REPOSITORY}:${PREFIX}-freebsd-base --push .
	@touch .docker-freebsd-base

docker-freebsd-amd64: .docker-freebsd-amd64
.docker-freebsd-amd64: docker-freebsd-base freebsd/amd64/Dockerfile
	@docker buildx build --platform linux/amd64,linux/arm64 --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-base -f ${CURDIR}/freebsd/amd64/Dockerfile -t ${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-amd64 -t ${REPOSITORY}:${PREFIX}-freebsd-amd64 --push .
	@touch .docker-freebsd-amd64

docker-freebsd-arm64: .docker-freebsd-arm64
.docker-freebsd-arm64: docker-freebsd-base freebsd/arm64/Dockerfile
	@docker buildx build --platform linux/amd64,linux/arm64 --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-base -f ${CURDIR}/freebsd/arm64/Dockerfile -t ${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-arm64 -t ${REPOSITORY}:${PREFIX}-freebsd-arm64 --push .
	@touch .docker-freebsd-arm64

docker-freebsd: docker-freebsd-amd64 docker-freebsd-arm64

docker-linux: .docker-linux
.docker-linux: docker-base linux/Dockerfile
	@docker buildx build --platform linux/amd64,linux/arm64 --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base -f ${CURDIR}/linux/Dockerfile -t ${REPOSITORY}:${PREFIX}-${VERSION}-linux -t ${REPOSITORY}:${PREFIX}-linux --push .
	@touch .docker-linux

docker-all: docker-base docker-darwin docker-darwin-sdk-extractor docker-freebsd docker-linux

podman-base: .podman-base
.podman-base: base/Dockerfile
	@buildah manifest create ${PREFIX}-${VERSION}-base
	@buildah bud --tag ${REPOSITORY}:${PREFIX}-${VERSION}-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-windows --tag ${REPOSITORY}:${PREFIX}-${VERSION}-web --manifest ${PREFIX}-${VERSION}-base --arch amd64 base
	@buildah bud --tag ${REPOSITORY}:${PREFIX}-${VERSION}-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-windows --tag ${REPOSITORY}:${PREFIX}-${VERSION}-web --manifest ${PREFIX}-${VERSION}-base --arch arm64 base
	@buildah manifest push --all ${PREFIX}-${VERSION}-base docker://${REPOSITORY}:${PREFIX}-${VERSION}-base
	@buildah manifest push --all ${PREFIX}-${VERSION}-base docker://${REPOSITORY}:${PREFIX}-${VERSION}-windows
	@buildah manifest push --all ${PREFIX}-${VERSION}-base docker://${REPOSITORY}:${PREFIX}-${VERSION}-web
	@touch .podman-base

podman-linux: .podman-linux
.podman-linux: .podman-base linux/Dockerfile
	@buildah manifest create ${PREFIX}-${VERSION}-linux
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-linux --manifest ${PREFIX}-${VERSION}-linux --arch amd64 linux
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-linux --manifest ${PREFIX}-${VERSION}-linux --arch arm64 linux
	@buildah manifest push --all ${PREFIX}-${VERSION}-linux docker://${REPOSITORY}:${PREFIX}-${VERSION}-linux
	@touch .podman-linux

podman-darwin: .podman-darwin
.podman-darwin: .podman-base darwin/Dockerfile
	@buildah manifest create ${PREFIX}-${VERSION}-darwin
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-darwin --manifest ${PREFIX}-${VERSION}-darwin --arch amd64 darwin
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-darwin --manifest ${PREFIX}-${VERSION}-darwin --arch arm64 darwin
	@buildah manifest push --all ${PREFIX}-${VERSION}-darwin docker://${REPOSITORY}:${PREFIX}-${VERSION}-darwin
	@touch .podman-darwin

podman-darwin-sdk: .podman-darwin-sdk
.podman-darwin-sdk: .podman-base darwin-with-sdk/Dockerfile
	@buildah manifest create ${PREFIX}-${VERSION}-darwin-sdk
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-darwin --tag ${REPOSITORY}:${PREFIX}-${VERSION}-darwin-sdk --manifest ${PREFIX}-${VERSION}-darwin-sdk --arch amd64 darwin-with-sdk
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-darwin --tag ${REPOSITORY}:${PREFIX}-${VERSION}-darwin-sdk --manifest ${PREFIX}-${VERSION}-darwin-sdk --arch arm64 darwin-with-sdk
	@buildah manifest push --all ${PREFIX}-${VERSION}-darwin-sdk docker://${REPOSITORY}:${PREFIX}-${VERSION}-darwin-sdk
	@touch .podman-darwin-sdk

podman-darwin-sdk-extractor: .podman-darwin-sdk-extractor
.podman-darwin-sdk-extractor: .podman-base darwin-sdk-extractor/Dockerfile
	@buildah manifest create ${PREFIX}-${VERSION}-darwin-sdk-extractor
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-darwin-sdk-extractor --manifest ${PREFIX}-${VERSION}-darwin-sdk-extractor --arch amd64 darwin-sdk-extractor
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-darwin-sdk-extractor --manifest ${PREFIX}-${VERSION}-darwin-sdk-extractor --arch arm64 darwin-sdk-extractor
	@buildah manifest push --all ${PREFIX}-${VERSION}-darwin-sdk-extractor docker://${REPOSITORY}:${PREFIX}-${VERSION}-darwin-sdk-extractor
	@touch .podman-darwin-sdk-extractor

podman-freebsd-base: .podman-freebsd
.podman-freebsd: .podman-base freebsd/base/Dockerfile
	@buildah manifest create ${PREFIX}-${VERSION}-freebsd-base
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-base --manifest ${PREFIX}-${VERSION}-freebsd-base --arch amd64 freebsd/base
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-base --manifest ${PREFIX}-${VERSION}-freebsd-base --arch arm64 freebsd/base
	@buildah manifest push --all ${PREFIX}-${VERSION}-freebsd-base docker://${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-base
	@touch .podman-freebsd

podman-freebsd-amd64: .podman-freebsd-amd64
.podman-freebsd-amd64: .podman-freebsd freebsd/amd64/Dockerfile
	@buildah manifest create ${PREFIX}-${VERSION}-freebsd-amd64
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-amd64 --manifest ${PREFIX}-${VERSION}-freebsd-amd64 --arch amd64 freebsd/amd64
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-amd64 --manifest ${PREFIX}-${VERSION}-freebsd-amd64 --arch arm64 freebsd/amd64
	@buildah manifest push --all ${PREFIX}-${VERSION}-freebsd-amd64 docker://${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-amd64
	@touch .podman-freebsd-amd64

podman-freebsd-arm64: .podman-freebsd-arm64
.podman-freebsd-arm64: .podman-freebsd freebsd/arm64/Dockerfile
	@buildah manifest create ${PREFIX}-${VERSION}-freebsd-arm64
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-arm64 --manifest ${PREFIX}-${VERSION}-freebsd-arm64 --arch amd64 freebsd/arm64
	@buildah bud --build-arg FYNE_CROSS_IMAGE_TAG=${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-base --tag ${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-arm64 --manifest ${PREFIX}-${VERSION}-freebsd-arm64 --arch arm64 freebsd/arm64
	@buildah manifest push --all ${PREFIX}-${VERSION}-freebsd-arm64 docker://${REPOSITORY}:${PREFIX}-${VERSION}-freebsd-arm64
	@touch .podman-freebsd-arm64

podman-freebsd: podman-freebsd-arm64 podman-freebsd-amd64

podman-all: podman-darwin podman-darwin-sdk-extractor podman-freebsd podman-linux

all: $(RUNNER)-all
